name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Линтинг
        run: |
          python -m ruff --version
          python -m ruff check . --fix
          python -m black --check .
      - name: Проверка типов
        run: python -m mypy .
      - name: Тесты
        run: python -m pytest -q
